version: "3.9"

services:
  streamlit:
    container_name: dashboard
    build:
      context: .
    restart: always
    volumes:
      - ./.streamlit:/app/.streamlit/
      - ./weatherdashboard:/app/weatherdashboard/
      - ./data:/app/data/
    command: ["streamlit", "run", "weatherdashboard/00_dashboard_introduction.py"]
    environment:
      - OPENROUTER_API_KEY=$OPENROUTER_API_KEY

    ports:
      - 8501:8501
    stdin_open: true
    tty: true
